name: clever_settings
description: Clever Settings is a Dart package that provides an easy way to manage and store settings for your application.
version: 0.1.0+1
repository: https://github.com/RoundedInfinity/clever_settings

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  clever_logger: ^1.1.0+1
  hive: ^2.2.3

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1
